# Add labels based on files changed
api:
  - api/**/*

admin:
  - admin/**/*

frontend:
  - admin/src/**/*

tests:
  - api/tests/**/*

documentation:
  - '**/*.md'
  - 'docs/**/*'

ci:
  - .github/**/*
  - docker/**/*
  - Makefile
  - docker-compose*.yml

docker:
  - docker/**/*
  - docker-compose*.yml
  - '**/Dockerfile'

dependencies:
  - api/composer.json
  - api/composer.lock
  - admin/package.json
  - admin/package-lock.json

database:
  - api/migrations/**/*
  - api/src/Entity/**/*
  - api/src/Repository/**/*

security:
  - api/config/packages/security.yaml
  - api/src/Security/**/*
