<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260120161411 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE refresh_tokens (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token VARCHAR(128) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ip_address VARCHAR(45) DEFAULT NULL, user_agent TEXT DEFAULT NULL, revoked BOOLEAN NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9BACE7E15F37A13B ON refresh_tokens (token)');
        $this->addSql('CREATE INDEX IDX_9BACE7E1A76ED395 ON refresh_tokens (user_id)');
        $this->addSql('CREATE INDEX idx_refresh_token ON refresh_tokens (token)');
        $this->addSql('CREATE INDEX idx_refresh_token_expires ON refresh_tokens (expires_at)');
        $this->addSql('ALTER TABLE refresh_tokens ADD CONSTRAINT FK_9BACE7E1A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE extra ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE extra ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE extra ALTER stock_quantity DROP DEFAULT');
        $this->addSql('ALTER TABLE extra ALTER low_stock_threshold DROP DEFAULT');
        $this->addSql('ALTER TABLE extra ALTER available DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN extra.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN extra.updated_at IS \'\'');
        $this->addSql('ALTER TABLE loyalty_account DROP CONSTRAINT fk_loyalty_account_user');
        $this->addSql('DROP INDEX idx_loyalty_account_user');
        $this->addSql('DROP INDEX idx_loyalty_account_tier');
        $this->addSql('ALTER TABLE loyalty_account ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE loyalty_account ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE loyalty_account ALTER points DROP DEFAULT');
        $this->addSql('ALTER TABLE loyalty_account ALTER total_points_earned DROP DEFAULT');
        $this->addSql('ALTER TABLE loyalty_account ALTER total_points_spent DROP DEFAULT');
        $this->addSql('ALTER TABLE loyalty_account ALTER tier DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN loyalty_account.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN loyalty_account.updated_at IS \'\'');
        $this->addSql('ALTER TABLE loyalty_account ADD CONSTRAINT FK_11F7BE17A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER INDEX loyalty_account_user_id_key RENAME TO UNIQ_11F7BE17A76ED395');
        $this->addSql('ALTER TABLE loyalty_reward DROP CONSTRAINT fk_loyalty_reward_free_product');
        $this->addSql('ALTER TABLE loyalty_reward ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE loyalty_reward ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE loyalty_reward ALTER type TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE loyalty_reward ALTER type DROP DEFAULT');
        $this->addSql('ALTER TABLE loyalty_reward ALTER active DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN loyalty_reward.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN loyalty_reward.updated_at IS \'\'');
        $this->addSql('ALTER TABLE loyalty_reward ADD CONSTRAINT FK_89AC2C075273B085 FOREIGN KEY (free_product_id) REFERENCES product (id) NOT DEFERRABLE');
        $this->addSql('ALTER INDEX idx_loyalty_reward_free_product RENAME TO IDX_89AC2C075273B085');
        $this->addSql('ALTER TABLE loyalty_transaction DROP CONSTRAINT fk_loyalty_transaction_reward');
        $this->addSql('ALTER TABLE loyalty_transaction DROP CONSTRAINT fk_loyalty_transaction_account');
        $this->addSql('ALTER TABLE loyalty_transaction DROP CONSTRAINT fk_loyalty_transaction_order');
        $this->addSql('DROP INDEX idx_loyalty_transaction_type');
        $this->addSql('ALTER TABLE loyalty_transaction ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE loyalty_transaction ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE loyalty_transaction ALTER type TYPE VARCHAR(255)');
        $this->addSql('COMMENT ON COLUMN loyalty_transaction.created_at IS \'\'');
        $this->addSql('ALTER TABLE loyalty_transaction ADD CONSTRAINT FK_4CE4AEC19B6B5FBA FOREIGN KEY (account_id) REFERENCES loyalty_account (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE loyalty_transaction ADD CONSTRAINT FK_4CE4AEC12B1C2395 FOREIGN KEY (related_order_id) REFERENCES "order" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE loyalty_transaction ADD CONSTRAINT FK_4CE4AEC1EB087160 FOREIGN KEY (redeemed_reward_id) REFERENCES loyalty_reward (id) NOT DEFERRABLE');
        $this->addSql('ALTER INDEX idx_loyalty_transaction_account RENAME TO IDX_4CE4AEC19B6B5FBA');
        $this->addSql('ALTER INDEX idx_loyalty_transaction_order RENAME TO IDX_4CE4AEC12B1C2395');
        $this->addSql('ALTER INDEX idx_loyalty_transaction_reward RENAME TO IDX_4CE4AEC1EB087160');
        $this->addSql('ALTER TABLE order_item_extra DROP CONSTRAINT fk_order_item_extra_order_item');
        $this->addSql('ALTER TABLE order_item_extra ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE order_item_extra ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE order_item_extra ALTER quantity DROP DEFAULT');
        $this->addSql('ALTER TABLE order_item_extra ADD CONSTRAINT FK_D442EBE0E415FB15 FOREIGN KEY (order_item_id) REFERENCES order_item (id) NOT DEFERRABLE');
        $this->addSql('ALTER INDEX idx_order_item_extra_order_item RENAME TO IDX_D442EBE0E415FB15');
        $this->addSql('ALTER INDEX idx_order_item_extra_extra RENAME TO IDX_D442EBE02B959FC6');
        $this->addSql('ALTER TABLE product ALTER ala_carte DROP DEFAULT');
        $this->addSql('ALTER TABLE product ALTER low_stock_threshold DROP DEFAULT');
        $this->addSql('ALTER TABLE product_extra DROP CONSTRAINT fk_product_extra_product');
        $this->addSql('ALTER TABLE product_extra DROP CONSTRAINT fk_product_extra_extra');
        $this->addSql('ALTER TABLE product_extra ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE product_extra ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE product_extra ALTER max_quantity DROP DEFAULT');
        $this->addSql('ALTER TABLE product_extra ADD CONSTRAINT FK_EC6376394584665A FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product_extra ADD CONSTRAINT FK_EC6376392B959FC6 FOREIGN KEY (extra_id) REFERENCES extra (id) NOT DEFERRABLE');
        $this->addSql('ALTER INDEX idx_product_extra_product RENAME TO IDX_EC6376394584665A');
        $this->addSql('ALTER INDEX idx_product_extra_extra RENAME TO IDX_EC6376392B959FC6');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE refresh_tokens DROP CONSTRAINT FK_9BACE7E1A76ED395');
        $this->addSql('DROP TABLE refresh_tokens');
        $this->addSql('ALTER TABLE extra ALTER id SET DEFAULT nextval(\'extra_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE extra ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE extra ALTER stock_quantity SET DEFAULT 0');
        $this->addSql('ALTER TABLE extra ALTER low_stock_threshold SET DEFAULT 10');
        $this->addSql('ALTER TABLE extra ALTER available SET DEFAULT true');
        $this->addSql('COMMENT ON COLUMN extra.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN extra.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE loyalty_account DROP CONSTRAINT FK_11F7BE17A76ED395');
        $this->addSql('ALTER TABLE loyalty_account ALTER id SET DEFAULT nextval(\'loyalty_account_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE loyalty_account ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE loyalty_account ALTER points SET DEFAULT 0');
        $this->addSql('ALTER TABLE loyalty_account ALTER total_points_earned SET DEFAULT 0');
        $this->addSql('ALTER TABLE loyalty_account ALTER total_points_spent SET DEFAULT 0');
        $this->addSql('ALTER TABLE loyalty_account ALTER tier SET DEFAULT \'bronze\'');
        $this->addSql('COMMENT ON COLUMN loyalty_account.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN loyalty_account.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE loyalty_account ADD CONSTRAINT fk_loyalty_account_user FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_loyalty_account_user ON loyalty_account (user_id)');
        $this->addSql('CREATE INDEX idx_loyalty_account_tier ON loyalty_account (tier)');
        $this->addSql('ALTER INDEX uniq_11f7be17a76ed395 RENAME TO loyalty_account_user_id_key');
        $this->addSql('ALTER TABLE loyalty_reward DROP CONSTRAINT FK_89AC2C075273B085');
        $this->addSql('ALTER TABLE loyalty_reward ALTER id SET DEFAULT nextval(\'loyalty_reward_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE loyalty_reward ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE loyalty_reward ALTER type TYPE VARCHAR(20)');
        $this->addSql('ALTER TABLE loyalty_reward ALTER type SET DEFAULT \'free_product\'');
        $this->addSql('ALTER TABLE loyalty_reward ALTER active SET DEFAULT true');
        $this->addSql('COMMENT ON COLUMN loyalty_reward.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN loyalty_reward.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE loyalty_reward ADD CONSTRAINT fk_loyalty_reward_free_product FOREIGN KEY (free_product_id) REFERENCES product (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX idx_89ac2c075273b085 RENAME TO idx_loyalty_reward_free_product');
        $this->addSql('ALTER TABLE loyalty_transaction DROP CONSTRAINT FK_4CE4AEC19B6B5FBA');
        $this->addSql('ALTER TABLE loyalty_transaction DROP CONSTRAINT FK_4CE4AEC12B1C2395');
        $this->addSql('ALTER TABLE loyalty_transaction DROP CONSTRAINT FK_4CE4AEC1EB087160');
        $this->addSql('ALTER TABLE loyalty_transaction ALTER id SET DEFAULT nextval(\'loyalty_transaction_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE loyalty_transaction ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE loyalty_transaction ALTER type TYPE VARCHAR(20)');
        $this->addSql('COMMENT ON COLUMN loyalty_transaction.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE loyalty_transaction ADD CONSTRAINT fk_loyalty_transaction_reward FOREIGN KEY (redeemed_reward_id) REFERENCES loyalty_reward (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE loyalty_transaction ADD CONSTRAINT fk_loyalty_transaction_account FOREIGN KEY (account_id) REFERENCES loyalty_account (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE loyalty_transaction ADD CONSTRAINT fk_loyalty_transaction_order FOREIGN KEY (related_order_id) REFERENCES "order" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_loyalty_transaction_type ON loyalty_transaction (type)');
        $this->addSql('ALTER INDEX idx_4ce4aec19b6b5fba RENAME TO idx_loyalty_transaction_account');
        $this->addSql('ALTER INDEX idx_4ce4aec12b1c2395 RENAME TO idx_loyalty_transaction_order');
        $this->addSql('ALTER INDEX idx_4ce4aec1eb087160 RENAME TO idx_loyalty_transaction_reward');
        $this->addSql('ALTER TABLE order_item_extra DROP CONSTRAINT FK_D442EBE0E415FB15');
        $this->addSql('ALTER TABLE order_item_extra ALTER id SET DEFAULT nextval(\'order_item_extra_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE order_item_extra ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE order_item_extra ALTER quantity SET DEFAULT 1');
        $this->addSql('ALTER TABLE order_item_extra ADD CONSTRAINT fk_order_item_extra_order_item FOREIGN KEY (order_item_id) REFERENCES order_item (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX idx_d442ebe0e415fb15 RENAME TO idx_order_item_extra_order_item');
        $this->addSql('ALTER INDEX idx_d442ebe02b959fc6 RENAME TO idx_order_item_extra_extra');
        $this->addSql('ALTER TABLE product ALTER ala_carte SET DEFAULT false');
        $this->addSql('ALTER TABLE product ALTER low_stock_threshold SET DEFAULT 10');
        $this->addSql('ALTER TABLE product_extra DROP CONSTRAINT FK_EC6376394584665A');
        $this->addSql('ALTER TABLE product_extra DROP CONSTRAINT FK_EC6376392B959FC6');
        $this->addSql('ALTER TABLE product_extra ALTER id SET DEFAULT nextval(\'product_extra_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE product_extra ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE product_extra ALTER max_quantity SET DEFAULT 5');
        $this->addSql('ALTER TABLE product_extra ADD CONSTRAINT fk_product_extra_product FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product_extra ADD CONSTRAINT fk_product_extra_extra FOREIGN KEY (extra_id) REFERENCES extra (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX idx_ec6376394584665a RENAME TO idx_product_extra_product');
        $this->addSql('ALTER INDEX idx_ec6376392b959fc6 RENAME TO idx_product_extra_extra');
    }
}
